// Mocks generated by Mockito 5.4.6 from annotations
// in app/test/golden_tests/products_list_screen_golden_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:app/core/utils/result.dart' as _i4;
import 'package:app/models/product.dart' as _i5;
import 'package:app/repositories/product_repository.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ProductRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductRepository extends _i1.Mock implements _i2.ProductRepository {
  MockProductRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<List<_i5.Product>>> getProducts() =>
      (super.noSuchMethod(
        Invocation.method(
          #getProducts,
          [],
        ),
        returnValue: _i3.Future<_i4.Result<List<_i5.Product>>>.value(
            _i6.dummyValue<_i4.Result<List<_i5.Product>>>(
          this,
          Invocation.method(
            #getProducts,
            [],
          ),
        )),
      ) as _i3.Future<_i4.Result<List<_i5.Product>>>);

  @override
  _i3.Future<_i4.Result<_i5.Product>> getProductById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProductById,
          [id],
        ),
        returnValue: _i3.Future<_i4.Result<_i5.Product>>.value(
            _i6.dummyValue<_i4.Result<_i5.Product>>(
          this,
          Invocation.method(
            #getProductById,
            [id],
          ),
        )),
      ) as _i3.Future<_i4.Result<_i5.Product>>);

  @override
  _i3.Future<_i4.Result<_i5.Product>> createProduct(_i5.Product? product) =>
      (super.noSuchMethod(
        Invocation.method(
          #createProduct,
          [product],
        ),
        returnValue: _i3.Future<_i4.Result<_i5.Product>>.value(
            _i6.dummyValue<_i4.Result<_i5.Product>>(
          this,
          Invocation.method(
            #createProduct,
            [product],
          ),
        )),
      ) as _i3.Future<_i4.Result<_i5.Product>>);

  @override
  _i3.Future<_i4.Result<_i5.Product>> updateProduct(_i5.Product? product) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProduct,
          [product],
        ),
        returnValue: _i3.Future<_i4.Result<_i5.Product>>.value(
            _i6.dummyValue<_i4.Result<_i5.Product>>(
          this,
          Invocation.method(
            #updateProduct,
            [product],
          ),
        )),
      ) as _i3.Future<_i4.Result<_i5.Product>>);

  @override
  _i3.Future<_i4.Result<void>> deleteProduct(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteProduct,
          [id],
        ),
        returnValue:
            _i3.Future<_i4.Result<void>>.value(_i6.dummyValue<_i4.Result<void>>(
          this,
          Invocation.method(
            #deleteProduct,
            [id],
          ),
        )),
      ) as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Stream<List<_i5.Product>> watchProducts() => (super.noSuchMethod(
        Invocation.method(
          #watchProducts,
          [],
        ),
        returnValue: _i3.Stream<List<_i5.Product>>.empty(),
      ) as _i3.Stream<List<_i5.Product>>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
